name: Destroy Event-Driven Microservices

# ONLY run this manually from the GitHub Actions tab
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js (for AWS CDK)
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.13
        run: uv python install 3.13

      - name: Install Dependencies
        run: uv sync

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::230150030147:role/aws-to-github # <-- REPLACE THIS
          aws-region: us-east-1

      - name: CDK Destroy
        # The --force flag is MANDATORY here. 
        # Without it, the pipeline will hang forever waiting for a [y/N] prompt.
        run:  uv run cdk destroy --all --force
